# Travis CI config, for https://travis-ci.org/denny/ShinyCMS-ruby

dist: bionic

language: ruby

rvm:
  - 2.6.6

cache: bundler

addons:
  postgresql: "10"

before_script:
  - bundle exec rails db:create
  - bundle exec rails db:schema:load
  - bundle exec rails assets:precompile

script:
  - bundle exec rspec
