# ShinyCMS ~ https://shinycms.org
#
# Copyright 2009-2026 Denny de la Haye ~ https://denny.me
#
# ShinyCMS is free software; you can redistribute it and/or modify it under the terms of the GPL (version 2 or later)

# Config for mkdocs, which builds https://docs.shinycms.org

site_name:        ShinyCMS
site_url:         http://docs.shinycms.org/
site_description: Documentation for users and developers of ShinyCMS (Ruby version)
site_author:      Denny de la Haye
copyright:        ShinyCMS is copyright 2009-2026 Denny de la Haye (denny.me)

repo_url: https://github.com/denny/ShinyCMS-ruby/
edit_uri: ''

theme: material

nav:
  - Installation, configuration, deployment:
    - Local installation: INSTALL.md
    - Configuration:      Configuration.md
    - Cloud hosting:      Cloud-Hosting.md
    - External services:  Services.md
    - Themes:             Themes.md
    - Demo site:          demo-site.md

    - tl,dr:              tldr.md

  - Features:
    - User Accounts:    Features/MainApp/UserAccounts.md
    - Admin Features:   Features/MainApp/admin-features.md

    - Basic 'brochure site' features:
      - Pages:          Features/Plugins/ShinyPages.md
      - Forms:          Features/Plugins/ShinyForms.md
      - Inserts:        Features/Plugins/ShinyInserts.md
      - Search:         Features/Plugins/ShinySearch.md

    - More advanced features:
      - Access control: Features/Plugins/ShinyAccess.md

    - Regular content updates:
      - Blog:           Features/Plugins/ShinyBlog.md
      - News section:   Features/Plugins/ShinyNews.md
      - Tags:           Features/MainApp/Tags.md

    - Send promotional emails:
      - Mailing Lists:  Features/Plugins/ShinyLists.md
      - Newsletters:    Features/Plugins/ShinyNewsletters.md

    - Build a community:
      - Comments:       Features/MainApp/Comments.md
      - Upvotes:        Features/MainApp/Upvotes.md
      - Profile Pages:  Features/Plugins/ShinyProfiles.md

    - Tracking/Analytics:
      - Email Stats:    Features/MainApp/EmailStats.md
      - Web Stats:      Features/MainApp/WebStats.md
      - Charts:         Features/MainApp/Charts.md

    - Configuration:
      - Feature Flags:  Features/MainApp/FeatureFlags.md
      - Site Settings:  Features/MainApp/SiteSettings.md

    - Other:
      - MJML:           Features/MainApp/mjml.md
      - Pagination:     Features/MainApp/pagination.md
      - Soft Delete:    Features/MainApp/soft-delete.md
      - Block Bots:     Features/MainApp/rack-attack
      - Rake tasks:     rake-tasks.md

  - Developer Documentation:
    - Index:            Developers/index.md

    - Contributing:     Contributing.md

    - Project Goals:    Developers/ProjectGoals.md

    - Testing:          Developers/Testing.md
    - Code Quality:     Developers/code-quality.md

    - Plugins:          Developers/Plugins.md

    - Helpers, Concerns, and other useful modules:
      - Overview:       Developers/Concerns-and-Helpers.md
      - Helpers:        Developers/helpers.md
      - Model Concerns: Developers/model-concerns.md
      - Controller Concerns: Developers/controller-concerns.md
      - Mailers:        Developers/Mailers.md
      - Other:          Developers/other-modules.md

    - Demo data:        Developers/demo-data.md
    - Rake tasks:       Developers/rake-tasks.md

    - Project Progress:
      - TODO:           Developers/TODO.md
      - In Progress:    Developers/in-progress.md
      - Done:           Developers/done.md

  - Licensing:          Licensing/index.md
  - Release notes:      release-notes.md
  - Credits:            credits.md
  - Code of Conduct:    code-of-conduct.md
  - Index:              index.md
